/**
 * CoinInfo
 * Coin Info application API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: b.khongi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.thiosin.cryptoinfo.data.network.coinlib.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param symbol
 * @param name
 * @param rank
 * @param price
 * @param delta24h
 */
@JsonClass(generateAdapter = true)
data class CoinLibListCoin(
    @Json(name = "symbol") val symbol: String,
    @Json(name = "name") val name: String,
    @Json(name = "rank") val rank: Int,
    @Json(name = "price") val price: String,
    @Json(name = "delta_24h") val delta24h: String
)