/**
 * CoinInfo
 * Coin Info application API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: b.khongi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.thiosin.cryptoinfo.data.network.coinlib.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class CoinLibCoinApiResponse(
    @Json(name = "symbol") val symbol: String,
    @Json(name = "price") val price: String,
    @Json(name = "low_24h") val low24h: String,
    @Json(name = "high_24h") val high24h: String,
    @Json(name = "delta_1h") val delta1h: String,
    @Json(name = "delta_24h") val delta24h: String,
    @Json(name = "delta_7d") val delta7d: String
)