language: android
dist: focal
os: linux
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2

addons:
  sonarcloud:
    organization: "khongi"
    token:
      secure: "q1HSGy9C3cHBnePlQt0BquDC3tohIzlHMoZFboZkgwzCG5gLInwlqRYzoEJLoGZeAiCu7/kMU/iF7IETVEGKakF1DZnlLA471nxkegpKXvimLPBpv57UZ53LDp7m4oJkyF91Qob93Db32roe+yPIJ8ihZOPCHWB3O3SNhPxkXRg4sxLDK4vwrmhMa2ORU58wCGzoud9iB8L87tamLVuLX+fP5x1T9JLLMt/s3JMUvcUQ6Hbayqt6UVqiW8Trldi7iArG8965A2yh8YSkmL2gWgPicBd0hM0BUnrl4nqG7GEFblLus3FT1b2AYADqJHJ7TbWpbBLGRrctjXfaOnSFdJC7hxKwxXImBmy7yPhcJZTK54JJCmT3eJtq+WzgPbvlJhFOwLUQsOTXEX5M/LJFIPIIv0V8FzXimXG2KdVVgOeeoYVQlq5+s+U2zmhkmpo3yNvvcVucCGVfg53opR43M0inYP9OAeu6qjI0eEmnJ32f8/bUfHuDyLaO9OPUrhiUFuURGksI7OpVl719zKbRf1+SPHqExpH6NrVzgmS4FJKsiU6kGYkkM+JgeSgcomNdJJ5JDdgje4HQMRHZ6jnFNeFKlbpLHE3d60POq9CQFmCpLXD3xMSMllYTtxTDQR6P/UKcGOsiYS67G6H/JUgL9yuqweM5ztXOrT1oRgDcnUw="

android:
  components:
    - tools
    - platform-tools
    - tools
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-x86-android-29
  licenses:
    # White list all the licenses.
    - '.+'

before_install:
  - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
  - export ANDROID_SDK_ROOT=${PATH}
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-${ANDROID_API_LEVEL}"
  - yes | sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}"

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

script:
  - mv apikey.sample.properties apikey.properties
  - ./gradlew assembleDevDebug testDevDebugUnitTestCoverage lintDevDebug detektDevDebug
  - sonar-scanner

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

notifications:
  email: false
  slack:
    secure: SCIgkPVO2/GQzbS2oLayYeTllr+kmhc/UsaBHD0fIoFMhDAhelZJlLiA8p1+whtZxYxCboph4W1QLkrM0wLPDpwFGLINxStoPM5mGrDzggTUkGIOTn9T20v3fqU8KFrCUK43EoBdEEV6gGxCMyZUrLwJJmFc9s9FZpKrBulTu3D7PQOy3q1wxFyCwyvd4Jx/Bdgp4hpufGDyjpFzO4R67zNWoXeZZrF0aWxvH+fHU8ffVV8KecXHKzCZ3ciD2/x2Wc6LafXjTAUqQRkfOG+N/Zfa9VhPlOJbWCdo6FvBWemNm0r2znzfsNncNPRwVScXk5mepNWnSGYXx/7p5oIGVMQdSD6LL0O6kBd3BWVVa6RzIab9y2TsomEmLDXjdHGZipgIj5Sg2BpRxa6ckrM6fPoaWmKFSYYYTwYYsndEIGMOGrw9mVq74r9uOv/r3SLEqcucVv0gT9uyBmc1SUPd+5jHCYV7FRoCz09kUmCck8Q0yXyM1GzWPDShMBtTuZLtJS2hPgYylj6jcPWGUSWYHRQ3qsXS1sGS4Sh7vYrr/P8vNP6x8I/F1DAeaMdcSRhUWgbj4OaJF1sIksg2BdzBknz9iEIig/EEl9Z7c3yLCDn47qbwTY1F+qsN4X+nrVFjLZClQ2RJksIjRBFpCS8nRFJtJan/jAoWjgIaY9dEl5E=
