/**
 * CoinInfo
 * Coin Info application API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: b.khongi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.thiosin.cryptoinfo.data.network.coinlayer.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param symbol
 * @param name
 * @param iconUrl
 */
@JsonClass(generateAdapter = true)
data class CoinLayerCoin(
    @Json(name = "symbol") val symbol: String,
    @Json(name = "name") val name: String,
    @Json(name = "icon_url") val iconUrl: String
)