/**
 * CoinInfo
 * Coin Info application API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: b.khongi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.thiosin.cryptoinfo.data.network.coinlayer.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param success
 * @param crypto
 * @param fiat
 */
@JsonClass(generateAdapter = true)
data class CoinLayerListApiResponse(
    @Json(name = "success") val success: Boolean,
    @Json(name = "crypto") val crypto: Map<String, CoinLayerCoin>,
    @Json(name = "fiat") val fiat: Map<String, String>
) {
}