/**
 * CoinInfo
 * Coin Info application API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: b.khongi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.thiosin.cryptoinfo.data.network.coinlib.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param symbol
 * @param volume24h
 * @param price
 * @param exchanges
 */
@JsonClass(generateAdapter = true)
data class CoinLibMarket(
    @Json(name = "symbol") val symbol: String,
    @Json(name = "volume_24h") val volume24h: String,
    @Json(name = "price") val price: String,
    @Json(name = "exchanges") val exchanges: Array<CoinLibExchange>
) {

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as CoinLibMarket

        if (symbol != other.symbol) return false
        if (volume24h != other.volume24h) return false
        if (price != other.price) return false
        if (!exchanges.contentEquals(other.exchanges)) return false

        return true
    }

    override fun hashCode(): Int {
        var result = symbol.hashCode()
        result = 31 * result + volume24h.hashCode()
        result = 31 * result + price.hashCode()
        result = 31 * result + exchanges.contentHashCode()
        return result
    }

}